service: githubactions-prueba
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: prod
  region: us-west-2

functions:
  generateRandomNumber:
    handler: src/handler.generateRandomNumber
    timeout: 60 #seconds
    memorySize: 128 #mb
