service: githubactions-prueba
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-west-2

functions:
  hello:
    handler: src/handler.generateRandomNumber
